config/routes.rb
Rails.application.routes.draw do
  #people conroller index method
  root 'people#index'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_person, only: [:show, :edit, :update, :destroy]
  
  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new(person_params)
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private

  def find_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:frist_name, :last_name, :avatar, :phone, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/index.html.erb
<h1 class='ui header'>People</h1>
<table class="ui celled table">
  <thead>
    <tr class='center aligned'>
      <th colspan='4'></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr class='center aligned'>
        <td>
          <img 
            class='ui avatar image small'
            src="https://robohash.org/<%= person.avatar %>?set=set4" 
            alt="robots"
          >
        </td>
        <td><%= link_to 'show', person_path(person) %></td>
        <td><%= link_to 'edit', edit_person_path(person) %></td>
        <td><%= link_to 'delete', person_path(person), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'new', new_person_path %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>